version: '3'

services:
  db:
    image: mongo:4.2.8
    container_name: db
    ports:
      - "4000:27017"
    restart: always
  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=isttaj
      - STORAGE_ACCESS_KEY=aA1UZ3x4NIAbPwVM1zR/DJitb+RMAuP+oIT0/1fYlMgqHIZn/ANh+jWITSfnYx9/Ckt+utDomGC6OfsNsMRLNg==
    restart: "no"

  video-streaming:
    image: video-streaming
    build:
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"
